name: Pipeline

on: [push]
env:
  ARTIFACT_NAME: 'Python_Artifact'
  ARTIFACT_ROOT: ${{ github.workspace }}
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - run: |
          python hello.py        

  build:
    needs: [test]
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_ROOT }}