name: Upload Artifact
env:
  ARTIFACT_NAME: 'Example_Artifact'
on: [push]
jobs:
  Print-Date-Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Print Date
        run: |
          printf -v date '%(%Y-%m-%d %H:%M:%S)T\n' -1
          echo $date
      - name: Checkout
      - uses: actions/checkout@v2
      - uses: actions/upload-artifact@v2
      -name: Upload Artifact
       with:
          name: ${{ env.ARTIFACT_NAME }}
          path: /