name: Upload Artifact
env:
  ARTIFACT_NAME: 'Example_Artifact'
  ARTIFACT_ROOT: ${{ github.workspace }}
on: [push]
jobs:
  Checkout-Upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_ROOT }}